-- Company extra fields
ALTER TABLE "Company" ADD COLUMN IF NOT EXISTS "code" TEXT;
ALTER TABLE "Company" ADD COLUMN IF NOT EXISTS "legalName" TEXT;
ALTER TABLE "Company" ADD COLUMN IF NOT EXISTS "email" TEXT;
ALTER TABLE "Company" ADD COLUMN IF NOT EXISTS "phone" TEXT;
ALTER TABLE "Company" ADD COLUMN IF NOT EXISTS "website" TEXT;
ALTER TABLE "Company" ADD COLUMN IF NOT EXISTS "logoUrl" TEXT;
ALTER TABLE "Company" ADD COLUMN IF NOT EXISTS "ntn" TEXT;
ALTER TABLE "Company" ADD COLUMN IF NOT EXISTS "regNo" TEXT;
ALTER TABLE "Company" ADD COLUMN IF NOT EXISTS "addressLine1" TEXT;
ALTER TABLE "Company" ADD COLUMN IF NOT EXISTS "addressLine2" TEXT;
ALTER TABLE "Company" ADD COLUMN IF NOT EXISTS "city" TEXT;
ALTER TABLE "Company" ADD COLUMN IF NOT EXISTS "stateRegion" TEXT;
ALTER TABLE "Company" ADD COLUMN IF NOT EXISTS "postalCode" TEXT;
ALTER TABLE "Company" ADD COLUMN IF NOT EXISTS "country" TEXT;
ALTER TABLE "Company" ADD COLUMN IF NOT EXISTS "notes" TEXT;

CREATE INDEX IF NOT EXISTS "Company_code_idx" ON "Company"("code");

-- Branch extra fields
ALTER TABLE "Branch" ADD COLUMN IF NOT EXISTS "email" TEXT;
ALTER TABLE "Branch" ADD COLUMN IF NOT EXISTS "phone" TEXT;
ALTER TABLE "Branch" ADD COLUMN IF NOT EXISTS "addressLine1" TEXT;
ALTER TABLE "Branch" ADD COLUMN IF NOT EXISTS "addressLine2" TEXT;
ALTER TABLE "Branch" ADD COLUMN IF NOT EXISTS "city" TEXT;
ALTER TABLE "Branch" ADD COLUMN IF NOT EXISTS "stateRegion" TEXT;
ALTER TABLE "Branch" ADD COLUMN IF NOT EXISTS "postalCode" TEXT;
ALTER TABLE "Branch" ADD COLUMN IF NOT EXISTS "country" TEXT;

-- User extra fields for admin creation
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "phone" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "passwordHash" TEXT;

